# Generated by Django 4.1.3 on 2022-12-01 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sourcerl',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 19, 33, 37, 76257, tzinfo=datetime.timezone.utc)),
        ),
    ]
