# Generated by Django 4.1.3 on 2022-12-02 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_sourcerl_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 8, 31, 45, 513978, tzinfo=datetime.timezone.utc)),
        ),
    ]
