# Generated by Django 4.1.3 on 2022-12-02 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 9, 6, 26, 314870, tzinfo=datetime.timezone.utc)),
        ),
    ]
